Assignments of Week-5
pesto-students/team-utkarsh-Somuesh pull request #6
Opened 2023-06-28 20:18 UTC by Somuesh

2023-07-08 10:19 UTC, thakurutkarsh22 requested changes

2023-07-08 10:19 UTC, thakurutkarsh22 commented on Week-5/DOM_window_object/Move the heart image with a timer/index.html
> +	   <script src="animate.js"></script>
in scripts or any other imports try to use Relative paths, these parts are absolute and in Production MODE or ALPHA mode (testing state) these thins will give error

2023-07-08 10:19 UTC, thakurutkarsh22 commented on Week-5/DOM_window_object/Move the heart image with a timer/animate.js
> +   const img = document.querySelector("img");
seclection of image like this will be time consuming,
Ids are fastest,
then search for classes 

Try to use these things 


If you want to search specifically by tags use document.getElementByTags()

2023-07-08 10:34 UTC, Somuesh commented on Week-5/DOM_window_object/Move the heart image with a timer/index.html
> +	   <script src="animate.js"></script>
Done

2023-07-08 10:34 UTC, Somuesh commented on Week-5/DOM_window_object/Move the heart image with a timer/animate.js
> +   const img = document.querySelector("img");
Done

2023-07-09 21:54 UTC, thakurutkarsh22 approved these changes
lgtm

2023-07-10 05:25 UTC, merged